#ifndef  JNI_SEARCHPY_H
#define  JNI_SEARCHPY_H
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_tgx_tina_android_plugin_contacts_search_SearchPy */
#undef __cplusplus
#include <stdlib.h>
#include <jni.h>
#include "AndroidEnv.h"
#include "SearchTools.h"
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_initInfos(JNIEnv *, jobject, jobjectArray, jint, jint);
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_search(JNIEnv *, jobject, jint, jstring, jintArray, jint, jint, jlong, jboolean);
JNIEXPORT jobjectArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getHightLights(JNIEnv *, jobject, jint, jintArray, jstring, jstring, jboolean);
JNIEXPORT jobjectArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getPyHightLights(JNIEnv *, jobject, jint, jintArray, jstring, jstring, jboolean);
JNIEXPORT jobjectArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getNameHightLights(JNIEnv *, jobject, jint, jintArray, jstring, jstring, jboolean);
JNIEXPORT jobjectArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getPhoneHightLights(JNIEnv *, jobject, jint, jintArray, jstring, jstring);
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getFirstPyPrimaryKeys(JNIEnv *, jobject, jint, jlong);
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getInfosPrimaryKeys(JNIEnv *, jobject, jint, jlong);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_modify(JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_insert(JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_delete(JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_dispose(JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_disposeAll(JNIEnv *, jobject);

#endif
