/*******************************************************************************
 * Copyright 2013 Zhang Zhuo(william@TinyGameX.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *******************************************************************************/
#ifndef  JNI_SEARCHPY_H
#define  JNI_SEARCHPY_H
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_tgx_tina_android_plugin_contacts_search_SearchPy */
#undef __cplusplus
#include <stdlib.h>
#include <jni.h>
#include "AndroidEnv.h"
#include "SearchTools.h"
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_initInfos(JNIEnv *, jobject, jobjectArray, jint, jint);
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_search(JNIEnv *, jobject, jint, jstring, jintArray, jint, jint, jlong, jboolean);
JNIEXPORT jobjectArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getHightLights(JNIEnv *, jobject, jint, jintArray, jstring, jstring, jboolean);
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getFirstPyPrimaryKeys(JNIEnv *, jobject, jint, jlong);
JNIEXPORT jintArray JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_getInfosPrimaryKeys(JNIEnv *, jobject, jint, jlong);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_modify(JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_insert(JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_delete(JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_dispose(JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_com_tgx_tina_android_plugin_contacts_search_SearchPy_disposeAll(JNIEnv *, jobject);

#endif
